version: '2'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        restart: always

    octosearch:
        image: octosearch:latest
        restart: always
        environment:
            BACKEND_SERVER: elastic:9200

