version: '2.0'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        restart: on-failure
        environment:
            - discovery.type=single-node

    octosearch:
        build: .
        image: octosearch:latest
        restart: on-failure
        environment:
            BACKEND_SERVER: elastic:9200
        ports:
            - "8080:80"
        volumes:
            - .:/usr/src/octosearch

    tika:
        image: logicalspark/docker-tikaserver
