version: '2'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        restart: on-failure

    octosearch:
        build: .
        image: octosearch:latest
        restart: always
        environment:
            BACKEND_SERVER: elastic:9200
