version: '2.0'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        restart: "no"
        environment:
            - discovery.type=single-node


    octosearch:
        build: .
        image: octosearch:latest
        restart: "no"
        environment:
            BACKEND_SERVER: elastic:9200
        ports:
            - "8080:80"
            - "5000:5000"
        volumes:
            - .:/usr/src/octosearch


    tika:
        restart: "no"
        image: logicalspark/docker-tikaserver
