version: '2.1'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
        restart: on-failure

    octosearch:
        build: .
        image: octosearch:latest
        restart: on-failure
        environment:
            BACKEND_SERVER: elastic:9200
        ports:
            - "8080:80"

    tika:
        image: logicalspark/docker-tikaserver
