version: '2.0'

services:
    elastic:
        extends:
            file: docker-compose-base.yml
            service: elastic
        environment:
            - cluster.routing.allocation.disk.threshold_enabled=false

    octosearch:
        extends:
            file: docker-compose-base.yml
            service: octosearch

        # install octosearch in dev mode
        command: sh -c "pip install -e . && util/docker-startup.sh"

    tika:
        extends:
            file: docker-compose-base.yml
            service: tika

    samba:
        image: dperson/samba
        command: sh -c "samba.sh -s \"testshare;/testshare\""
        volumes:
            - ./testshare:/testshare
